/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as IndexRouteImport } from './routes/index'

const PlayersLazyRouteImport = createFileRoute('/players')()

const PlayersLazyRoute = PlayersLazyRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/players.lazy').then((d) => d.Route))
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams': typeof TeamsRoute
  '/players': typeof PlayersLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teams': typeof TeamsRoute
  '/players': typeof PlayersLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teams': typeof TeamsRoute
  '/players': typeof PlayersLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teams' | '/players'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teams' | '/players'
  id: '__root__' | '/' | '/teams' | '/players'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamsRoute: typeof TeamsRoute
  PlayersLazyRoute: typeof PlayersLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamsRoute: TeamsRoute,
  PlayersLazyRoute: PlayersLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
